sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t layziebone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true layziebone/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dockerr"
  env: "Dockerr-env"
  bucket_name: "elasticbeanstalk-ap-south-1-866409760586"
  bucket_path: "dockerr"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
